name: Publish to GPR
on:
  release:
    types: ["created"]
jobs:
  build:
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        node-version: [13.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: yarn install
    - name: Build
      run: yarn run build
  publish-gpr:
    runs-on: "ubuntu-latest"
    needs: ["build"]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://npm.pkg.github.com
        scope: "@kipr"
    - name: Publish to GPR
      run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}